[package]
name = "slam_common"
version = "0.1.0"
edition = "2021"

workspace = "../../"
[dependencies]
optigy = { path = "../../" }
nalgebra = {version="0.32.3", features=["compare"]}
sophus-rs= { git = "https://github.com/Lishen1/sophus-rs.git",  branch="lie-only" }
num = "0.4.1"
