[package]
name = "optigy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faer-core     = "0.9.1"
faer-lu       = "0.9.1"
faer-qr       = "0.9.1"
faer-cholesky = "0.9.1"
faer-svd      = "0.9.1"

num-traits = "0.2.15"
rustc-hash = { version = "1.1", default-features = false }